name: Prymal Skus Shopify
run-name: ${{ github.actor }} - Skus Shopify
on: 
  push:
    paths:
      - '**/data_pipelines/shopify/skus/**'

jobs:
  shopify_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r prymal/data_pipelines/shopify/requirements.txt
    
      - name: Publish Latest Skus CSV to S3
        env: 
          S3_PRYMAL:  ${{ secrets.S3_PRYMAL }}
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_USER_ARN:  ${{ secrets.AWS_USER_ARN }}
        run: python prymal/data_pipelines/shopify/skus/shopify_skus.py 

      - run: echo "Job status - ${{ job.status }}."
