name: Prymal Shopify Extraction Backfill
run-name: ${{ github.actor }} - Shopify Extraction Backfill
on: 
  push:
jobs:
  shopify_etl_backfill:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r prymal/data_pipelines/shopify/requirements.txt
    
      - name: Backfill Shopify Orders & Line Items
        env: 
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          S3_PRYMAL:  ${{ secrets.S3_PRYMAL }}
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_USER_ARN:  ${{ secrets.AWS_USER_ARN }}
        run: python prymal/data_pipelines/shopify/order_data_backfill/shopify_extraction_backfill.py 

      - name: Run Shopify Glue Crawlers
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        run: python prymal/data_pipelines/shopify/order_data/shopify_crawlers.py 
        

      - run: echo "Job status - ${{ job.status }}."
