name: TRANSFORM - shopify_qty_sold_by_sku_daily
run-name: ${{ github.actor }} - TRANSFORM - shopify_qty_sold_by_sku_daily
on: 
  push:
    paths:
      - '**/transformations/shopify_qty_sold_by_sku_daily/**'
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM every day

jobs:
  transform_shopify_qty_sold_by_sku_daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r prymal/transformations/requirements.txt
    
      - name: TRANSFORM - shopify_qty_sold_by_sku_daily
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_ACCOUNT_ID:  ${{ secrets.AWS_ACCOUNT_ID }}
        run: python prymal/transformations/shopify_qty_sold_by_sku_daily/shopify_qty_sold_by_sku_daily.py 

      - run: echo "Job status - ${{ job.status }}."
